-- ============================================================================
-- MARKETSPACE COMPLETE DATABASE SCHEMA MIGRATION
-- ============================================================================

-- Enable UUID extension if not already enabled
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 1. PROFILES TABLE (Linked 1-to-1 with Supabase Auth users)
CREATE TABLE IF NOT EXISTS public.profiles (
    user_id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    username TEXT,
    email TEXT,
    phone_number TEXT,
    avatar_url TEXT,
    pending_otp TEXT,
    onboarding_choice TEXT,
    phone_verified BOOLEAN DEFAULT false,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. STORES TABLE (Merchant Storefronts - Owned by User)
CREATE TABLE IF NOT EXISTS public.stores (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID UNIQUE REFERENCES public.profiles(user_id) ON DELETE CASCADE,
    shop_name TEXT NOT NULL,
    description TEXT,
    category TEXT,
    address TEXT,
    whatsapp TEXT,
    logo TEXT,
    cover TEXT,
    accent_color TEXT DEFAULT '#2563eb',
    announcement_bar TEXT,
    collections JSONB DEFAULT '[]'::jsonb,
    customer_care JSONB DEFAULT '{}'::jsonb,
    catalog JSONB DEFAULT '[]'::jsonb,
    ads JSONB DEFAULT '[]'::jsonb,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Migration for existing stores table:
ALTER TABLE public.stores
  ADD COLUMN IF NOT EXISTS operation_type TEXT DEFAULT 'omnichannel',
  ADD COLUMN IF NOT EXISTS accent_color TEXT DEFAULT '#2563eb',
  ADD COLUMN IF NOT EXISTS announcement_bar TEXT,
  ADD COLUMN IF NOT EXISTS collections JSONB DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS customer_care JSONB DEFAULT '{}'::jsonb;

-- Migration for listings table:
ALTER TABLE public.listings
  ADD COLUMN IF NOT EXISTS lowest_acceptable_price NUMERIC,
  ADD COLUMN IF NOT EXISTS delivery_paid_by TEXT DEFAULT 'buyer';

-- 3. LISTINGS TABLE (Products & Services - Belongs to User, Optionally to Store)
CREATE TABLE IF NOT EXISTS public.listings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES public.profiles(user_id) ON DELETE CASCADE,
    store_id UUID REFERENCES public.stores(id) ON DELETE SET NULL, -- NULLABLE: Set if posted as part of a store!
    title TEXT NOT NULL,
    description TEXT,
    price NUMERIC NOT NULL,
    category TEXT NOT NULL,
    location TEXT,
    status TEXT DEFAULT 'Available',
    listing_type TEXT DEFAULT 'item',
    condition TEXT DEFAULT 'Used - Good',
    images TEXT[] DEFAULT '{}',
    sponsored BOOLEAN DEFAULT false,
    available_colors TEXT[] DEFAULT '{}',
    last_renewed_at TIMESTAMPTZ DEFAULT NOW(),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. SAVED_LISTINGS TABLE (User Favorites & Bookmarks)
CREATE TABLE IF NOT EXISTS public.saved_listings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES public.profiles(user_id) ON DELETE CASCADE,
    listing_id BIGINT REFERENCES public.listings(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT unique_user_listing_saved UNIQUE (user_id, listing_id)
);

-- 5. CHATS TABLE (Buyer-Seller Direct Message Threads)
CREATE TABLE IF NOT EXISTS public.chats (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    buyer_id UUID REFERENCES public.profiles(user_id) ON DELETE CASCADE,
    seller_id UUID REFERENCES public.profiles(user_id) ON DELETE CASCADE,
    listing_id BIGINT REFERENCES public.listings(id) ON DELETE SET NULL,
    title TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. MESSAGES TABLE (Individual Messages Inside a Chat)
CREATE TABLE IF NOT EXISTS public.messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chat_id BIGINT REFERENCES public.chats(id) ON DELETE CASCADE,
    sender_id UUID REFERENCES public.profiles(user_id) ON DELETE CASCADE,
    content TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 7. NOTIFICATIONS TABLE (Targeted Alerts or Broadcasts)
CREATE TABLE IF NOT EXISTS public.notifications (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID REFERENCES public.profiles(user_id) ON DELETE CASCADE, -- NULLABLE: NULL means broadcast to all users!
    title TEXT NOT NULL,
    body TEXT NOT NULL,
    time TEXT DEFAULT 'Just now',
    unread BOOLEAN DEFAULT true,
    link_url TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 8. REVIEWS TABLE (Ratings & Reviews for Stores AND Individual Peers)
CREATE TABLE IF NOT EXISTS public.reviews (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    reviewer_id UUID REFERENCES public.profiles(user_id) ON DELETE CASCADE,
    store_id UUID REFERENCES public.stores(id) ON DELETE CASCADE, -- NULLABLE: filled if reviewing a store
    target_user_id UUID REFERENCES public.profiles(user_id) ON DELETE CASCADE, -- NULLABLE: filled if reviewing an individual peer
    rating INTEGER CHECK (rating >= 1 AND rating <= 5),
    comment TEXT NOT NULL,
    reply TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================================================
-- INDEXES FOR MAXIMUM QUERY PERFORMANCE
-- ============================================================================
CREATE INDEX IF NOT EXISTS idx_listings_user_id ON public.listings(user_id);
CREATE INDEX IF NOT EXISTS idx_listings_store_id ON public.listings(store_id);
CREATE INDEX IF NOT EXISTS idx_saved_listings_user_id ON public.saved_listings(user_id);
CREATE INDEX IF NOT EXISTS idx_chats_buyer_id ON public.chats(buyer_id);
CREATE INDEX IF NOT EXISTS idx_chats_seller_id ON public.chats(seller_id);
CREATE INDEX IF NOT EXISTS idx_messages_chat_id ON public.messages(chat_id);
CREATE INDEX IF NOT EXISTS idx_notifications_user_id ON public.notifications(user_id);
CREATE INDEX IF NOT EXISTS idx_reviews_store_id ON public.reviews(store_id);
CREATE INDEX IF NOT EXISTS idx_reviews_target_user_id ON public.reviews(target_user_id);
CREATE INDEX IF NOT EXISTS idx_reviews_reviewer_id ON public.reviews(reviewer_id);

-- ============================================================================
-- ROW LEVEL SECURITY (RLS) POLICIES
-- ============================================================================

-- Enable RLS on all tables
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.stores ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.listings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.saved_listings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.chats ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reviews ENABLE ROW LEVEL SECURITY;

-- Public Read Policies
CREATE POLICY "Public Read Profiles" ON public.profiles FOR SELECT USING (true);
CREATE POLICY "Public Read Stores" ON public.stores FOR SELECT USING (true);
CREATE POLICY "Public Read Listings" ON public.listings FOR SELECT USING (true);
CREATE POLICY "Public Read Reviews" ON public.reviews FOR SELECT USING (true);

-- User Self Management Policies
CREATE POLICY "User Manage Profile" ON public.profiles FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "User Manage Store" ON public.stores FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "User Manage Listings" ON public.listings FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "User Manage Saved Listings" ON public.saved_listings FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "User Read Chats" ON public.chats FOR SELECT USING (auth.uid() = buyer_id OR auth.uid() = seller_id);
CREATE POLICY "User Insert Chats" ON public.chats FOR INSERT WITH CHECK (auth.uid() = buyer_id);
CREATE POLICY "User Read Messages" ON public.messages FOR SELECT USING (
    EXISTS (SELECT 1 FROM public.chats WHERE id = messages.chat_id AND (buyer_id = auth.uid() OR seller_id = auth.uid()))
);
CREATE POLICY "User Send Messages" ON public.messages FOR INSERT WITH CHECK (auth.uid() = sender_id);
CREATE POLICY "User Read Notifications" ON public.notifications FOR SELECT USING (user_id IS NULL OR auth.uid() = user_id);
CREATE POLICY "User Update Notifications" ON public.notifications FOR UPDATE USING (user_id IS NULL OR auth.uid() = user_id);
CREATE POLICY "User Write Reviews" ON public.reviews FOR INSERT WITH CHECK (auth.uid() = reviewer_id);

-- Secure RPC Function to let users delete their own auth account & cascading data
CREATE OR REPLACE FUNCTION delete_my_account()
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
    DELETE FROM auth.users WHERE id = auth.uid();
END;
$$;
